app_objs += $(addprefix apps/calculation-rpn/,\
  app.o\
  calculation.o\
  calculation_store.o\
  edit_expression_controller.o\
  stack_view_cell.o\
  history_controller.o\
  local_context.o\
  scrollable_expression_view.o\
  selectable_table_view.o\
  text_field.o\
)

app_images += apps/calculation/calculation_icon.png

